'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Locale
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Mountains.Locale", GetType(Locale).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cloud Curliness (Value: .
        '''</summary>
        Public Shared ReadOnly Property CloudCurliness() As String
            Get
                Return ResourceManager.GetString("CloudCurliness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cloud Speed (Value: .
        '''</summary>
        Public Shared ReadOnly Property CloudSpeed() As String
            Get
                Return ResourceManager.GetString("CloudSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to exit without saving
        '''Are you sure you want to proceed?.
        '''</summary>
        Public Shared ReadOnly Property ExitWithoutSavingMsg() As String
            Get
                Return ResourceManager.GetString("ExitWithoutSavingMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit Without Saving?.
        '''</summary>
        Public Shared ReadOnly Property ExitWithoutSavingTitle() As String
            Get
                Return ResourceManager.GetString("ExitWithoutSavingTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resolution Ratio (Value: .
        '''</summary>
        Public Shared ReadOnly Property ResolutionRatio() As String
            Get
                Return ResourceManager.GetString("ResolutionRatio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Settings.
        '''</summary>
        Public Shared ReadOnly Property SaveSettings() As String
            Get
                Return ResourceManager.GetString("SaveSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terrain Frequency (Value: .
        '''</summary>
        Public Shared ReadOnly Property TerrainFrequency() As String
            Get
                Return ResourceManager.GetString("TerrainFrequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tranquility Screensaver Suite - Clouds &amp; Mountains Screensaver Settings.
        '''</summary>
        Public Shared ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weather Scale (Value: .
        '''</summary>
        Public Shared ReadOnly Property WeatherScale() As String
            Get
                Return ResourceManager.GetString("WeatherScale", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
